config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'posts#index'
  resources :posts do
    resources :comments, :except => [:index, :show]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates :name, :presence => true
  validates :description, :presence => true
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments

  validates :name, :presence => true
  validates :description, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController <ApplicationController
  def index
    @comment = Comment.all
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(post_params)
    if @comment.save
      flash[:notice] = "Comment was added successfully."
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(post_params)
      flash[:notice] = "Comment updated"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Comment deleted"
    redirect_to posts_path
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private
  def comment_params
    params.require(:comment).permit(:name, :description)
  end
end

app/controllers/post_controller.rb
class PostsController <ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @posts = Post.new
  end

  def create
    @posts = Post.new(list_params)
    if @posts.save
      flash[:notice] = "Post was added successfully."
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @posts = Post.find(params[:id])
  end

  def update
    @posts = Post.find(params[:id])
    if @posts.update(list_params)
      flash[:notice] = "Post updated"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @posts = Post.find(params[:id])
    @posts.destroy
    flash[:notice] = "Post deleted"
    redirect_to posts_path
  end

  def show
    @posts = Post.find(params[:id])
  end

  private
  def list_params
    params.require(:posts).permit(:name, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController <ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @posts = Post.new
  end

  def create
    @posts = Post.new(post_params)
    if @posts.save
      flash[:notice] = "Post was added successfully."
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @posts = Post.find(params[:id])
  end

  def update
    @posts = Post.find(params[:id])
    if @posts.update(post_params)
      flash[:notice] = "Post updated"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @posts = Post.find(params[:id])
    @posts.destroy
    flash[:notice] = "Post deleted"
    redirect_to posts_path
  end

  def show
    @posts = Post.find(params[:id])
  end

  private
  def post_params
    params.require(:post).permit(:title, :description, :name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<% render('layouts/errors', :object => @comment) %>

<%= form_for [@post, @comment] do |f| %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <p><%= f.submit %></p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit <%= @comment.description %></h1>


<%= render 'form' %>

app/views/comments/new.html.erb
<% content_for(:title, "Add New Comments") %>

<h1>Add Comments: <%= @comment.name %></h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Sorry, please repost</h3>

  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>

  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:alert] %>
<%= flash[:notice] %>

<%= yield %>

</body>
</html>

app/views/lists/_form.html.erb
<%= render "layouts/errors", :object => @list %>

<%= form_for @list do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.submit %>
<% end %>

app/views/lists/edit.html.erb
<% content_for(:title, "Edit List | To Do") %>

<h1>Edit <%= @post.name %> </h1>

<%= render "form" %>

<%= link_to "back", posts_path %>

app/views/posts/_form.html.erb
<%= render "layouts/errors", :object => @posts %>

<%= form_for @posts do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.label :name %>
  <%= f.text_area :name %>

  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<% content_for(:title, "Edit Post") %>

<h1>Edit <%= @post.title %> </h1>

<%= render "form" %>

<%= link_to "back", post_path %>

app/views/posts/index.html.erb
<% content_for(:title, "ShimCity Blog") %>

<h1>Posts</h1>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to post.title, post_path(post) %> <p>Created By: <%= post.name %>
    </li>
  <% end %>
</ul>

<br />
<%= link_to "New Post", new_post_path %>

app/views/posts/new.html.erb
<% content_for(:title, "New Post for ShimCity Blog") %>

<h1>New Post</h1>

<%= render "form" %>

app/views/posts/show.html.erb
<% content_for(:title, "ShimCity Blog" ) %>

<h1><%= @posts.title %></h1>

<h4><%= @posts.description %></h4>


<% if @posts.comments.any? %>
  <h4>Here are the comments for this list:</h4>

  <ul>
    <% @posts.comments.each do |comment| %>
    <li>
      <%= comment.description %> |
      <%= link_to "Edit", edit_post_comment_path(@posts, comment) %> |
      <%= link_to "Delete", post_comment_path(@posts, comment),
                              :data => {:confirm => "Are you sure?",
                                        :method => "delete"} %>
    </li>
    <% end %>
  </ul>
<% else %>
  <p>
    There are no comments yet!
  </p>
<% end %>

<p>
  <%= link_to "Add a comment", new_post_comment_path(@posts) %>
</p>

<p>
  <%= link_to "Edit", edit_post_path(@posts) %>
</p>
<p>
  <%= link_to "Delete", post_path(@posts),
                        :data => {:confirm => "Are you sure?",
                                      :method => "delete"}%>
</p>
<p>
  <%= link_to "Return to Posts", posts_path %>
</p>